# Generated by Django 4.0.4 on 2022-06-11 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='Identificador del cliente')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos del cliente')),
                ('correo', models.CharField(max_length=200, verbose_name='Correo del cliente')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion del cliente')),
            ],
        ),
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id_medio_pago', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Identificador del medio de pago')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre del medio de pago')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Identificador del producto')),
                ('nombre', models.IntegerField(max_length=100, verbose_name='Nombre del producto')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción del producto')),
                ('precio', models.IntegerField(verbose_name='Precio del producto')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Identificador de la venta')),
                ('monto', models.IntegerField(verbose_name='Monto total')),
                ('fecha', models.CharField(max_length=10, verbose_name='Fecha de la venta')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('medio_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mediopago')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle_venta', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Identificador del detalle de venta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venta')),
            ],
        ),
    ]
